version: "3.2"
volumes:
  db_data: {}
services:
  mysql_db:
    image: mysql:5.7
    container_name: wordpress_db
    hostname: wordpress_db
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=wordpress
    volumes:
    - db_data:/var/lib/mysql
#    - ./conf.d:/etc/mysql/conf.d
    network_mode: "host"
    restart: always
